name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Auto-format imports and code with isort & black
        run: |
          echo "▶ Running isort and black to auto-fix imports/code"
          isort .
          black .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: apply isort & black fixes" || echo "No changes to commit"

      - name: Check import order with isort
        run: |
          echo "▶ Checking import order (isort --check-only)"
          isort --check-only .

      - name: Check code formatting with black
        run: |
          echo "▶ Checking code formatting (black --check)"
          black --check .
